// Ground Chunks;
	pub const DEBUGUI_GroundChunkOutlines: bool = true;
	pub const DEBUGUI_GroundChunkCheckerboards: bool = false;
	pub const DEBUGUI_RecomputeGroundChunksOnExeChange: bool = true;
// Particles;
	pub const DEBUGUI_ParticleTest: bool = false;
	pub const DEBUGUI_ParticleGrid: bool = false;
// Renderer;
	pub const DEBUGUI_TestWeirdDrawBufferSize: bool = false;
	pub const DEBUGUI_ShowLightingSamples: bool = false;
	// Camera;
		pub const DEBUGUI_UseDebugCamera: bool = false;
		pub const DEBUGUI_DebugCameraDistance: f32 = 50;
		pub const DEBUGUI_UseRoomBasedCamera: bool = false;
pub const DEBUGUI_UseSpaceOutlines: bool = false;
pub const DEBUGUI_FamiliarFollowsHero: bool = true;
