// Ground Chunks;
	pub const DEBUGUI_GroundChunkOutlines = true;
	pub const DEBUGUI_GroundChunkCheckerboards = false;
	pub const DEBUGUI_RecomputeGroundChunksOnExeChange = true;
// Particles;
	pub const DEBUGUI_ParticleTest = false;
	pub const DEBUGUI_ParticleGrid = false;
// Renderer;
	pub const DEBUGUI_TestWeirdDrawBufferSize = false;
	pub const DEBUGUI_ShowLightingSamples = false;
	// Camera;
		pub const DEBUGUI_UseDebugCamera = true;
		pub const DEBUGUI_UseRoomBasedCamera = false;
pub const DEBUGUI_UseSpaceOutlines = false;
pub const DEBUGUI_FamiliarFollowsHero = false;
