const std = @import("std");
const config = @import("config");

// TODO (Manav): improve code and optimize it.

const timed_fn_gen =
    \\
    \\{s}// AUTOGENERATED ----------------------------------------------------------
    \\{s}var __t_blk__{} = Debug.TIMED_FUNCTION__impl({}, @src()).Init({s}
    \\{s}defer __t_blk__{}.End();
    \\{s}// AUTOGENERATED ----------------------------------------------------------
;

const begin_blk_gen =
    \\
    \\{s}// AUTOGENERATED ----------------------------------------------------------
    \\{s}Platform.BEGIN_BLOCK__impl({}, @src(), {s}
    \\{s}// AUTOGENERATED ----------------------------------------------------------
;

const end_blk_gen =
    \\
    \\{s}// AUTOGENERATED ----------------------------------------------------------
    \\{s}Platform.END_BLOCK__impl({}, {s}
    \\{s}// AUTOGENERATED ----------------------------------------------------------
;

const frame_marker_gen =
    \\
    \\{s}// AUTOGENERATED ----------------------------------------------------------
    \\{s}Platform.FRAME_MARKER__impl({}, @src(), {s}
    \\{s}// AUTOGENERATED ----------------------------------------------------------
;

const timed_blk_gen =
    \\
    \\{s}// AUTOGENERATED ----------------------------------------------------------
    \\{s}var __t_blk__{} = Debug.TIMED_BLOCK__impl({}, @src()).Init({s}
    \\{s}defer __t_blk__{}.End();
    \\{s}// AUTOGENERATED ----------------------------------------------------------
;

// No-prefix variants for use inside handmade_debug.zig itself (no Debug. qualifier needed)
const timed_fn_gen_no_prefix =
    \\
    \\{s}// AUTOGENERATED ----------------------------------------------------------
    \\{s}var __t_blk__{} = TIMED_FUNCTION__impl({}, @src()).Init({s}
    \\{s}defer __t_blk__{}.End();
    \\{s}// AUTOGENERATED ----------------------------------------------------------
;

const timed_blk_gen_no_prefix =
    \\
    \\{s}// AUTOGENERATED ----------------------------------------------------------
    \\{s}var __t_blk__{} = TIMED_BLOCK__impl({}, @src()).Init({s}
    \\{s}defer __t_blk__{}.End();
    \\{s}// AUTOGENERATED ----------------------------------------------------------
;

const counter_gen =
    \\
    \\{s}// AUTOGENERATED ----------------------------------------------------------
    \\{s}{{
    \\{s}    return {};
    \\{s}}}
    \\{s}// AUTOGENERATED ----------------------------------------------------------
;

const tag = "AUTOGENERATED";

const timed_fn_call_site = "Debug.TIMED_FUNCTION(";
const begin_blk_call_site = "Platform.BEGIN_BLOCK(";
const end_blk_call_site = "Platform.END_BLOCK(";
const frame_marker_call_site = "Platform.FRAME_MARKER(";
const timed_blk_call_site = "Debug.TIMED_BLOCK(";

const timed_fn_call_site_no_prefix = "TIMED_FUNCTION(";
const timed_blk_call_site_no_prefix = "TIMED_BLOCK(";

const counter_site = "pub inline fn __COUNTER__() comptime_int";

/// No. of lines the debug imports are required to be within, from the top.
const LINES_SEARCHED_FOR_DEBUG_IMPORT = 2;

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer std.debug.assert(gpa.deinit() == .ok);
    const allocator = gpa.allocator();

    var counter: u32 = 0;

    // TODO (Manav): this is ugly
    var file = try std.fs.cwd().openFile("./../win32_handmade.zig", .{ .mode = .read_write });
    defer file.close();

    const file_size = try file.getEndPos();

    const buffer = try allocator.alloc(u8, file_size);
    defer allocator.free(buffer);

    _ = try file.readAll(buffer);

    if (try processFile(allocator, "win32_handmade.zig", buffer, &counter)) |result| {
        defer allocator.free(result.content);

        // Truncate the file and write the modified content
        try file.seekTo(0);
        try file.setEndPos(0);
        try file.writeAll(result.content);
    }

    _ = try processDir(allocator, "./", &counter);

    var debug_file = try std.fs.cwd().openFile("./handmade_debug.zig", .{ .mode = .read_write });
    defer debug_file.close();

    try processDebug(allocator, &debug_file, &counter);

    std.debug.print("Prepocessing Summary:\n  Generated {} <...>__impl() calls.\n", .{if (config.PROFILE) counter else 0});
}

fn processDir(allocator: std.mem.Allocator, dir_path: []const u8, counter: *u32) !bool {
    var found = false;
    var dir = try std.fs.cwd().openDir(dir_path, .{ .iterate = true });
    defer dir.close();

    var iter = dir.iterate();

    while (try iter.next()) |entry| {
        switch (entry.kind) {
            .file => {
                if (!std.mem.endsWith(u8, entry.name, ".zig")) {
                    continue;
                } else {
                    var file = try std.fs.cwd().openFile(entry.name, .{ .mode = .read_write });
                    defer file.close();

                    for (0..LINES_SEARCHED_FOR_DEBUG_IMPORT) |_| {
                        if (try file.deprecatedReader().readUntilDelimiterOrEofAlloc(allocator, '\n', 1000)) |line| {
                            defer allocator.free(line);
                            if (std.mem.indexOf(u8, line, "const Debug = @import(")) |_| {
                                found = true;

                                try file.seekTo(0);

                                const file_size = try file.getEndPos();

                                const buffer = try allocator.alloc(u8, file_size);
                                defer allocator.free(buffer);

                                _ = try file.readAll(buffer);

                                if (try processFile(allocator, entry.name, buffer, counter)) |result| {
                                    defer allocator.free(result.content);

                                    // Truncate the file and write the modified content
                                    try file.seekTo(0);
                                    try file.setEndPos(0);
                                    try file.writeAll(result.content);
                                }

                                break;
                            }
                        }
                    }
                }
            },
            else => continue,
        }
    }

    return found;
}

const process_file_result = struct {
    name: []const u8 = "",
    pos: usize = 0,
    content: []const u8 = "",
};

fn processFile(allocator: std.mem.Allocator, _: []const u8, buffer: []const u8, counter: *u32) !?process_file_result {
    var result: process_file_result = .{};

    var out_buffer = std.array_list.Managed(u8).init(allocator);
    defer out_buffer.deinit();

    var found_call = false;

    var reader = std.io.fixedBufferStream(buffer);

    var tag_count: u32 = 0;

    while (try reader.reader().readUntilDelimiterOrEofAlloc(allocator, '\n', 1000)) |line| {
        defer allocator.free(line);

        if (std.mem.indexOf(u8, line, tag)) |_| {
            tag_count = (tag_count + 1) % 2;

            continue;
        }

        if (tag_count == 0) {
            // TODO (Manav): this is ugly
            if (std.mem.indexOf(u8, line, timed_fn_call_site)) |pos| {
                found_call = true;

                const indent = line[0..pos];
                const argument = line[pos + timed_fn_call_site.len ..];

                const gen_blk = try std.fmt.allocPrint(allocator, timed_fn_gen, .{ indent, indent, counter.*, counter.*, argument, indent, counter.*, indent });
                defer allocator.free(gen_blk);

                // std.debug.print("Overwriting line:\n{s}\nwith:\n{s}\n\n", .{ line, gen_blk });

                counter.* += 1;

                try out_buffer.appendSlice(line);
                if (config.PROFILE) {
                    try out_buffer.appendSlice(gen_blk);
                }
                try out_buffer.append('\n');
            } else if (std.mem.indexOf(u8, line, timed_blk_call_site)) |pos| {
                found_call = true;

                const indent = line[0..pos];
                const argument = line[pos + timed_blk_call_site.len ..];

                const gen_blk = try std.fmt.allocPrint(allocator, timed_blk_gen, .{ indent, indent, counter.*, counter.*, argument, indent, counter.*, indent });
                defer allocator.free(gen_blk);

                // std.debug.print("Overwriting line:\n{s}\nwith:\n{s}\n\n", .{ line, gen_blk });

                counter.* += 1;

                try out_buffer.appendSlice(line);
                if (config.PROFILE) {
                    try out_buffer.appendSlice(gen_blk);
                }
                try out_buffer.append('\n');
            } else if (std.mem.indexOf(u8, line, frame_marker_call_site)) |pos| {
                found_call = true;

                const indent = line[0..pos];
                const argument = line[pos + frame_marker_call_site.len ..];

                const gen_blk = try std.fmt.allocPrint(allocator, frame_marker_gen, .{ indent, indent, counter.*, argument, indent });
                defer allocator.free(gen_blk);

                // std.debug.print("Overwriting line:\n{s}\nwith:\n{s}\n\n", .{ line, gen_blk });

                counter.* += 1;

                try out_buffer.appendSlice(line);
                if (config.PROFILE) {
                    try out_buffer.appendSlice(gen_blk);
                }
                try out_buffer.append('\n');
            } else if (std.mem.indexOf(u8, line, begin_blk_call_site)) |pos| {
                found_call = true;

                const indent = line[0..pos];
                const argument = line[pos + begin_blk_call_site.len ..];

                const gen_blk = try std.fmt.allocPrint(allocator, begin_blk_gen, .{ indent, indent, counter.*, argument, indent });
                defer allocator.free(gen_blk);

                // std.debug.print("Overwriting line:\n{s}\nwith:\n{s}\n\n", .{ line, gen_blk });

                try out_buffer.appendSlice(line);
                if (config.PROFILE) {
                    try out_buffer.appendSlice(gen_blk);
                }
                try out_buffer.append('\n');
            } else if (std.mem.indexOf(u8, line, end_blk_call_site)) |pos| {
                found_call = true;

                const indent = line[0..pos];
                const argument = line[pos + end_blk_call_site.len ..];

                const gen_blk = try std.fmt.allocPrint(allocator, end_blk_gen, .{ indent, indent, counter.*, argument, indent });
                defer allocator.free(gen_blk);

                // std.debug.print("Overwriting line:\n{s}\nwith:\n{s}\n\n", .{ line, gen_blk });

                counter.* += 1;

                try out_buffer.appendSlice(line);
                if (config.PROFILE) {
                    try out_buffer.appendSlice(gen_blk);
                }
                try out_buffer.append('\n');
            } else {
                try out_buffer.appendSlice(line);
                try out_buffer.append('\n');
            }
        } else {
            // std.debug.print("Skipping.\n", .{});

            continue;
        }
    }

    if (!found_call) return null;

    result.content = try out_buffer.toOwnedSlice();
    return result;
}

fn processDebug(allocator: std.mem.Allocator, file: *std.fs.File, counter: *u32) !void {
    const file_size = try file.getEndPos();

    const buffer = try allocator.alloc(u8, file_size);
    defer allocator.free(buffer);

    _ = try file.readAll(buffer);

    // Pre-scan: count TIMED_FUNCTION/TIMED_BLOCK calls not inside AUTOGENERATED blocks.
    // Needed because __COUNTER__ is defined before those calls in the file, so we must
    // know the total before we reach it in the main pass.
    var debug_call_count: u32 = 0;
    {
        var pre_reader = std.io.fixedBufferStream(buffer);
        var pre_tag_count: u32 = 0;
        while (try pre_reader.reader().readUntilDelimiterOrEofAlloc(allocator, '\n', 1000)) |line| {
            defer allocator.free(line);
            if (std.mem.indexOf(u8, line, tag)) |_| {
                pre_tag_count = (pre_tag_count + 1) % 2;
                continue;
            }
            if (pre_tag_count == 0) {
                if (std.mem.indexOf(u8, line, timed_fn_call_site_no_prefix)) |_| {
                    debug_call_count += 1;
                } else if (std.mem.indexOf(u8, line, timed_blk_call_site_no_prefix)) |_| {
                    debug_call_count += 1;
                }
            }
        }
    }

    const total_counter = counter.* + debug_call_count;
    var running_counter = counter.*;

    var out_buffer = std.array_list.Managed(u8).init(allocator);
    defer out_buffer.deinit();

    var found_call = false;

    var reader = std.io.fixedBufferStream(buffer);

    var tag_count: u32 = 0;

    while (try reader.reader().readUntilDelimiterOrEofAlloc(allocator, '\n', 1000)) |line| {
        defer allocator.free(line);

        if (std.mem.indexOf(u8, line, tag)) |_| {
            tag_count = (tag_count + 1) % 2;

            continue;
        }

        if (tag_count == 0) {
            if (std.mem.indexOf(u8, line, counter_site)) |pos| {
                found_call = true;

                const indent = line[0..pos];

                const gen_blk = try std.fmt.allocPrint(allocator, counter_gen, .{ indent, indent, indent, if (config.PROFILE) total_counter else 0, indent, indent });
                defer allocator.free(gen_blk);

                // std.debug.print("Overwriting line:\n{s}\nwith:\n{s}\n\n", .{ line, gen_blk });

                try out_buffer.appendSlice(line);
                try out_buffer.appendSlice(gen_blk);

                try out_buffer.append('\n');
            } else if (std.mem.indexOf(u8, line, timed_fn_call_site_no_prefix)) |pos| {
                found_call = true;

                const indent = line[0..pos];
                const argument = line[pos + timed_fn_call_site_no_prefix.len ..];

                const gen_blk = try std.fmt.allocPrint(allocator, timed_fn_gen_no_prefix, .{ indent, indent, running_counter, running_counter, argument, indent, running_counter, indent });
                defer allocator.free(gen_blk);

                // std.debug.print("Overwriting line:\n{s}\nwith:\n{s}\n\n", .{ line, gen_blk });

                running_counter += 1;

                try out_buffer.appendSlice(line);
                if (config.PROFILE) {
                    try out_buffer.appendSlice(gen_blk);
                }
                try out_buffer.append('\n');
            } else if (std.mem.indexOf(u8, line, timed_blk_call_site_no_prefix)) |pos| {
                found_call = true;

                const indent = line[0..pos];
                const argument = line[pos + timed_blk_call_site_no_prefix.len ..];

                const gen_blk = try std.fmt.allocPrint(allocator, timed_blk_gen_no_prefix, .{ indent, indent, running_counter, running_counter, argument, indent, running_counter, indent });
                defer allocator.free(gen_blk);

                // std.debug.print("Overwriting line:\n{s}\nwith:\n{s}\n\n", .{ line, gen_blk });

                running_counter += 1;

                try out_buffer.appendSlice(line);
                if (config.PROFILE) {
                    try out_buffer.appendSlice(gen_blk);
                }
                try out_buffer.append('\n');
            } else {
                try out_buffer.appendSlice(line);
                try out_buffer.append('\n');
            }
        } else {
            // std.debug.print("Skipping.\n", .{});

            continue;
        }
    }

    if (!found_call) return;

    const file_contents = try out_buffer.toOwnedSlice();
    defer allocator.free(file_contents);

    try file.seekTo(0);
    try file.setEndPos(0);
    try file.writeAll(file_contents);

    counter.* = total_counter;
}
